#!/bin/bash

sshpass() {
tee<<pyfile>/tmp/typ.py
#!/usr/bin/python3
import os,sys,time
from pynput.keyboard import Key,Controller
jp=Controller()
time.sleep(6)
jp.type('$pass')
jp.press(Key.enter)
jp.release(Key.enter)
pyfile

python3 /tmp/typ.py &
}

sshadd() {
[ ! -f ~/.okssh  ] && mkdir -p ~/.okssh
tee <<sshtxet>~/.okssh/$1
ssh=$2
port=$3
sshtxet
ssh-copy-id "$2"
}
sshadd_a() {
 [ -f ~/.okssh/$1 ] && . ~/.okssh/$1
[ -z "$port" ] &&port=22
if [ ok == ok$ssh ];then 
echo  user@server port
read ssh port && sshadd $1 $ssh $port
fi
}

case $1 in
add) if [ ok4 == "ok$#" ];then
sshadd $2 $3 $4;fi
if [ ok3 == "ok$#" ];then
sshadd $2 $3 ;fi
exit ;;
esac

case $1 in
www)sshadd_a www ck@www.linux-ren.org 22
[ -z "$port" ] &&port=22
ssh ck@www.linux-ren.org
exit ;;
d*)if [ ok1 == "ok$#" ];then
sshadd_a $1
ssh -p $port $ssh 
exit;fi;;
setup)
if [ $(id -u) != 0 ];then
sudo bash "$0" "$@"
exit;fi
case "$0" in
lrossh|/bin*) ;;
*)cp "$0" /bin/lrossh && chmod +x /bin/lrossh ;;
esac ;;
esac


for cs in $1 $2 wc ;do
if [ "ok4" == "ok$#" ];then
case $cs in
ul)FILE=$4 ;;
dl)FILE=$3 ;;
www) [ -f ~/.okssh/$cs ] && . ~/.okssh/$cs
scpdir="ck@www.linux-ren.org:$FILE" ;;
d*) [ -f ~/.okssh/$cs ] && . ~/.okssh/$cs
scpdir=$ssh:$FILE ;;
wc)
case $1 in
ul)sshadd_a $2
scp -P $port $3 $scpdir
exit ;;
dl)sshadd_a $2
scp -P $port $scpdir $4 
exit ;;
esac ;;
esac
fi;done
