#!/bin/bash

sshpass() {
tee<<pyfile>/tmp/typ.py
#!/usr/bin/python3
import os,sys,time
from pynput.keyboard import Key,Controller
jp=Controller()
time.sleep(6)
jp.type('$pass')
jp.press(Key.enter)
jp.release(Key.enter)
pyfile

python3 /tmp/typ.py &
}

sshadd() {
[ ! -f ~/.okssh  ] && mkdir -p ~/.okssh
[ -z "$3" ] &&port=22
[ ! -z "$3" ] &&port=$3
tee <<sshtxet>~/.okssh/$1
ssh=$2
port=$port
sshtxet
ssh-copy-id "$2" -p $port
}

sshadd_a() {
[ -f ~/.okssh/$1 ] && . ~/.okssh/$1
if [ ok == ok$ssh ];then 
echo  user@server port
read ssh port && sshadd $1 $ssh $port
fi
}
vncadd() {
[ ! -f ~/.okssh  ] && mkdir -p ~/.okssh
 [ -f ~/.okssh/$1 ] && . ~/.okssh/$1
if [ -z "$vnc" ];then
if [ -z "$2" ];then 
echo  server 
read vnc  
else vnc="$2";fi
tee <<sshtxet>~/.okssh/$1
vnc=$vnc
port=$port
sshtxet
tee <<desk>~/桌面/RD-$1.desktop
[Desktop Entry]
Exec=/bin/lrossh $1
GenericName[zh_CN]=远程 $1
GenericName=远程 $1
Name[zh_CN]=远程 $1
Name=RDP & VNC $1
Path=
StartupNotify=false
Terminal=false
Type=Application
desk
fi

}

case $1 in
add) if [ ok4 == "ok$#" ];then
sshadd $2 $3 $4;fi
if [ ok3 == "ok$#" ];then
sshadd $2 $3 ;fi
if [ ok2 == "ok$#" ];then
[ -f ~/.okssh/$2 ] && . ~/.okssh/$2 && sshadd $ssh $port ;fi
exit ;;
edit)
 [ -f ~/.okssh/$2 ] && nano ~/.okssh/$2 ;
exit ;
esac

case $1 in
www)sshadd_a www ok@www.linuxren.org.cn 22
[ -z "$port" ] &&port=22
ssh ok@www.linuxren.org.cn
exit ;;
d*)if [ ok1 == "ok$#" ];then
sshadd_a $1
ssh -p $port $ssh 
exit;fi;;
v*) vncadd $1 $2
krdc $vnc ;;
setup)
if [ $(id -u) != 0 ];then
sudo bash "$0" "$@"
exit;fi
case "$0" in
lrossh|/bin*) ;;
*)cp "$0" /bin/lrossh && chmod +x /bin/lrossh ;;
esac ;;
esac


for cs in $1 $2 wc ;do
if [ "ok4" == "ok$#" ];then
case $cs in
ul)FILE=$4 ;;
dl)FILE=$3 ;;
www) [ -f ~/.okssh/$cs ] && . ~/.okssh/$cs
scpdir="ok@www.linux-ren.org.cn:$FILE" ;;
d*) [ -f ~/.okssh/$cs ] && . ~/.okssh/$cs
scpdir=$ssh:$FILE ;;
wc)
case $1 in
ul)sshadd_a $2
scp -r -P $port $3 $scpdir
exit ;;
dl)sshadd_a $2
scp -r -P $port $scpdir $4 
exit ;;
esac ;;
esac
fi;done
