#!/bin/bash
### BEGIN INIT INFO
# Provides:          okkautorun
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: OKRun
# Description:       Auto Start Run Server By sjchenkan
### END INIT INFO
export PATH=/bin:/sbin:$PATH
[ -f /etc/okautorun ]&& sh /etc/okautorun &

 [ $(id -u) != "0" ] && sudo bash" $0" "$@" &&  exit
case "$1" in
start|restart|status|reload|stop) echo OK;;
edit)nano /etc/okautorun ;;
*)cp -rf $0 /etc/init.d/okautorun
chmod 777 /etc/init.d/okautorun
case "$5" in
/bin*|okasutorun)
cp -rf $0 /bin/okautorun
chmod 777 /bin/okautorun ;;
esac
echo "$@" >>/etc/okautorun
systemctl enable okautorun >/dev/null
systemctl start okautorun
;;
esac

