#!/bin/bash
### BEGIN INIT INFO
# Provides:          okkipv6n
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: OKDns
# Description:       Auto Start Dns Server By sjchenkan
### END INIT INFO
export PATH=/bin:/sbin:$PATH
Noipdns() {
if [ -f /etc/noip.cnf ];then
. /etc/noip.cnf
while [ k = k ]; do
cd /tmp
[ -f ip6.log ]&& old=$(cat /tmp/ip6.log)
new=$(ip a| awk '/inet6/')
if [ "$old" != "$new" ]; then
! wget -o v6.tmp "http://v6.meibu.com/v6.asp?name=$addr&pwd=$pass"  && rm ip6.log -rf && old=""
[ -f v6.tmp ] && echo "$new"> /tmp/ip6.log
echo [OK]
else
echo "==same!"
fi
sleep 90
done
fi
}
case "$1" in
start) Noipdns &
;;
stop) echo not stop ;;
setup) 
[ $(id -u) != "0" ] && sudo bash $0 setup
cp -rf $0 /etc/init.d/okipv6
chmod 777 /etc/init.d/okipv6
echo "请输入‘你的域名 密码’"&& read addr pass
[ -z "$addr" ] && exit
[ -z "$pass" ] && bash $0 setup
tee <<conf>/etc/noip.cnf
addr=$addr
pass=$pass
conf
systemctl enable okipv6 ;;
esac
