#!/bin/bash
### BEGIN INIT INFO
# Provides:          okkipv6n
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      1
# Short-Description: OKDns
# Description:       Auto Start Dns Server By sjchenkan
### END INIT INFO
export PATH=/bin:/sbin:$PATH
Noipdns() {
while [ k = k ]; do
cd /tmp
[ -f ip6.log ]&& old=$(cat /tmp/ip6.log)
new=$(ip -6 a| awk '/global/')
echo "$new"|while read ipa ip6 ipb ipc;do
ip -6 route add default via "$ip6"
type -p route>/dev/null && route -A inet6 add default gw "$ip6"
done
if [ -f /etc/noip.cnf ];then
. /etc/noip.cnf
if [ "$old" != "$new" ]; then
! wget -Ov6.log -ov6.tmp "http://v6.meibu.com/v6.asp?name=$addr&pwd=$pass"  && rm ip6.log -rf && old=""
[ -f ip6.log ] && echo "$new"> /tmp/ip6.log
echo [OK]
else
echo "==same!"
fi;fi
sleep 90
done
}
case "$1" in
start) Noipdns & ;;
restart|status|reload|stop) echo not stop ;;
*) [ $(id -u) != "0" ] && sudo bash $0 setup &&  exit
cp -rf $0 /etc/init.d/okipv6
chmod 777 /etc/init.d/okipv6
systemctl enable okipv6 >/dev/null
systemctl start okipv6
echo "请输入‘你的域名 密码’"&& read addr pass
[ -z "$addr" ] && exit
[ -z "$pass" ] && bash $0 setup && exit
tee <<conf>/etc/noip.cnf
addr=$addr
pass=$pass
conf
;;
esac
